name: Build and Commit OpenNext Output (Bun)

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Build project
        env:
          RA_USERNAME: ${{ secrets.RA_USERNAME }}
          RA_API_KEY: ${{ secrets.RA_API_KEY }}
        run: |
          echo "🔧 Build started with injected secrets"
          echo "RA_USERNAME present: ${RA_USERNAME:+yes}"
          echo "RA_API_KEY present: ${RA_API_KEY:+yes}"
          rm -rf .open-next .next
          bunx opennextjs-cloudflare build

      - name: Commit build output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .open-next
          git diff --cached --quiet || git commit -m "ci: add .open-next build output [skip ci]"
          git push